server:
  port: 8080
  context-path: /reward

spring:
  datasource:
#    Internal
    url: jdbc:mariadb://10.178.230.98:3306/hotspot_reward
#    External
#    url: jdbc:mariadb://169.56.96.234:3306/hotspot_reward
    driverClassName: org.mariadb.jdbc.Driver
    username: hotspot_reward_user
    password: ureka97@ma
    
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        sql_comments: true

logging:
  level: 
    org.hibernate.type: info