    apiVersion: apps/v1beta1
    kind: Deployment
    metadata:
      name: hotspot-reward # deployment name -> kubectl get deployment
      labels:
        app: hotspot-reward
    spec:
      replicas: 1 # number of pod
      selector:
        matchLabels:
          app: hotspot-reward
      template:
        metadata:
          labels:
            app: hotspot-reward
        spec:
          containers:
          - name: hotspot-reward
            image: dep-dev-registry.cloudzcp.io/sample/hotspot-reward:latest
          imagePullSecrets:
          - name: jonas-secret 
    #        ports:
    #        - containerPort: 8080