    apiVersion: v1
    kind: Service
    metadata:
      labels:
        app: hotspot-reward
      name: hotspot-reward
      namespace: dex-dev
    spec:
      ports:
      - port: 80
        protocol: TCP
        targetPort: 8080
      selector:
        app: hotspot-reward